---
abstract: 'Shows gray favicon for development env'
author:
  - 'Fuji, Goro <gfuji@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.7, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-DevFavicon
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Middleware::DevFavicon:
    file: lib/Plack/Middleware/DevFavicon.pm
    version: 0.02
requires:
  Imager: 0
  Plack: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/gfx/Plack-Middleware-DevFavicon/issues
  homepage: https://github.com/gfx/Plack-Middleware-DevFavicon
  repository: git://github.com/gfx/Plack-Middleware-DevFavicon.git
version: 0.02
x_contributors:
  - 'Fuji, Goro <goro-fuji@cookpad.com>'
